#!/bin/bash

# Detect system language
user=$(users | awk '{print $1}')

if test -e "/home/$user/.config/plasma-localerc" ; then
	language=$(grep -r LANGUAGE= "/home/$user/.config/plasma-localerc" | cut -d"=" -f 2- | cut -d":" -f -1 | tr [A-Z] [a-z] | sed 's/_/-/')

	if [ -z $language ]; then
    	language=$(grep -r LANG= "/home/$user/.config/plasma-localerc" | cut -d"=" -f 2- | cut -d"." -f -1 | tr [A-Z] [a-z] | sed 's/_/-/')
	fi

elif test -e "/home/$user/.config/user-dirs.locale" ; then
    language=$(cat "/home/$user/.config/user-dirs.locale" | tr [A-Z] [a-z] | sed 's/_/-/')

else
    language=$(echo $LANG | tr [A-Z] [a-z] | sed 's/_/-/' | cut -d"." -f -1)
fi

# Choose the translation of the icon in the system
# tray according to the user's language
function check_up_title() {
    if [[ $language == *"pt-br"* ]]; then
        echo "Verificando atualizações..."

    elif [[ $language == *"pt-pt"* ]]; then
        echo "Verificando atualizações..."

    elif [[ $language == *"pt"* ]]; then
        echo "Verificando atualizações..."

    elif [[ $language == *"en-us"* ]]; then
        echo "Checking for updates..."

    else
        echo "Checking for updates..."
    fi
}

function available_up_title() {
    if [[ $language == *"pt-br"* ]]; then
        if test -e "/tmp/regataos-update/number-apps.txt"; then
            echo "Atualizações disponíveis! $(cat /tmp/regataos-update/number-apps.txt)"
        else
            echo "Atualizações disponíveis!"
        fi

    elif [[ $language == *"pt-pt"* ]]; then
        if test -e "/tmp/regataos-update/number-apps.txt"; then
            echo "Atualizações disponíveis! $(cat /tmp/regataos-update/number-apps.txt)"
        else
            echo "Atualizações disponíveis!"
        fi

    elif [[ $language == *"pt"* ]]; then
        if test -e "/tmp/regataos-update/number-apps.txt"; then
            echo "Atualizações disponíveis! $(cat /tmp/regataos-update/number-apps.txt)"
        else
            echo "Atualizações disponíveis!"
        fi

    elif [[ $language == *"en-us"* ]]; then
        if test -e "/tmp/regataos-update/number-apps.txt"; then
            echo "Updates available! $(cat /tmp/regataos-update/number-apps.txt)"
        else
            echo "Updates available!"
        fi

    else
        if test -e "/tmp/regataos-update/number-apps.txt"; then
            echo "Updates available! $(cat /tmp/regataos-update/number-apps.txt)"
        else
            echo "Updates available!"
        fi
    fi
}

function install_up_title() {
    if [[ $language == *"pt-br"* ]]; then
        echo "Instalando atualizações..."

    elif [[ $language == *"pt-pt"* ]]; then
        echo "Instalando atualizações..."

    elif [[ $language == *"pt"* ]]; then
        echo "Instalando atualizações..."

    elif [[ $language == *"en-us"* ]]; then
        echo "Installing updates..."

    else
        echo "Installing updates..."
    fi
}

function open_up_mg() {
    if [[ $language == *"pt-br"* ]]; then
        echo "Abrir o gerenciador de atualizações"

    elif [[ $language == *"pt-pt"* ]]; then
        echo "Abrir o gerenciador de atualizações"

    elif [[ $language == *"pt"* ]]; then
        echo "Abrir o gerenciador de atualizações"

    elif [[ $language == *"en-us"* ]]; then
        echo "Open update manager"

    else
        echo "Open update manager"
    fi
}

function update_sys() {
    if [[ $language == *"pt-br"* ]]; then
        echo "Instalar atualizações"

    elif [[ $language == *"pt-pt"* ]]; then
        echo "Instalar atualizações"

    elif [[ $language == *"pt"* ]]; then
        echo "Instalar atualizações"

    elif [[ $language == *"en-us"* ]]; then
        echo "Install updates"

    else
        echo "Install updates"
    fi
}

# Run options
case $1 in
    "-check-up-title") check_up_title
      ;;
    "-available-up-title") available_up_title
      ;;
    "-install-up-title") install_up_title
      ;;
    "-open-up-mg") open_up_mg
      ;;
    "-update-sys") update_sys
      ;;
   *) echo "Invalid option!"
      exit 1
      ;;
esac
