#!/bin/sh

function check_update() {
    notify-send -i regataos-up-mg-none-notify -u normal -a 'Regata OS Update' "Checking for updates..." "Searching for system updates."
}

function no_update() {
    notify-send -i regataos-up-mg-none-notify -u normal -a 'Regata OS Update' "No updates available!" "There are no updates available for the system."
}

function show_update() {
    if test -e "/tmp/regataos-update/number-apps.txt"; then
        number_update=$(cat /tmp/regataos-update/number-apps.txt)
        if [ $(echo $number_update | sed 's/(\|)//g') -gt 1 ]; then
            notify-send -i regataos-up-mg-none-notify -u normal -a 'Regata OS Update' "Updates available $number_update!" "Automatic updates are disabled."
        else
            notify-send -i regataos-up-mg-none-notify -u normal -a 'Regata OS Update' "Update available $number_update!" "Automatic updates are disabled."
        fi
	else
		notify-send -i regataos-up-mg-none-notify -u normal -a 'Regata OS Update' "Update available $number_update!" "Automatic updates are disabled."
    fi
}

function up_system() {
    notify-send -i regataos-up-mg-none-notify -u normal -a 'Regata OS Update' "Installing updates..." "Automatic update is enabled."
}

# Run options
case $1 in
    "-check-up") check_update
        ;;
    "-no-up") no_update
        ;;
    "-show-up") show_update
        ;;
    "-up-system") up_system
        ;;
   *) echo "Invalid option!"
      exit 1
      ;;
esac
